services:
  db:
    image: ghcr.io/baosystems/postgis:16-3.4
    container_name: ais_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:5432"
    restart: unless-stopped

volumes:
  postgres_data: